# Generated by Django 5.2 on 2026-02-27 09:16

import django.db.models.deletion
import filer.fields.image
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0001_initial"),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="photo",
            name="created",
        ),
        migrations.RemoveField(
            model_name="photo",
            name="filename",
        ),
        migrations.RemoveField(
            model_name="photo",
            name="name",
        ),
        migrations.RemoveField(
            model_name="photo",
            name="updated",
        ),
        migrations.AlterField(
            model_name="photo",
            name="image",
            field=filer.fields.image.FilerImageField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="image",
                to=settings.FILER_IMAGE_MODEL,
                verbose_name="Изображение",
            ),
        ),
    ]
