# Generated by Django 5.2 on 2026-02-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0002_remove_photo_created_remove_photo_filename_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="photo",
            options={
                "ordering": ["order"],
                "verbose_name": "Изображение",
                "verbose_name_plural": "Изображения(-ий)",
            },
        ),
        migrations.AddField(
            model_name="photo",
            name="order",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
