# Generated by Django 5.2 on 2026-02-27 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0003_alter_photo_options_photo_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="photo",
            options={
                "ordering": ["order"],
                "verbose_name": "Изображение",
                "verbose_name_plural": "Изображения",
            },
        ),
        migrations.AlterField(
            model_name="photo",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, default=0, verbose_name="Сортировка"
            ),
        ),
    ]
